### ISSUE TITLE
project-config command line option does not work

### ISSUE THREAD

**Issue by tgerulaitis** [Space48/magedbm2#36] opened 2019-07-11 09:03 UTC
It appears that the `--project-config` option is not effective. When specified:

1. The project config is still read from the current working directory
2. If the file specified with `--project-config` does not exist, no error is thrown, even though looking at the code it should throw an error

This might be caused by the configuration now being loaded in `di.php` while the `--project-config` option is only processed in `\Meanbee\Magedbm2\Application::loadProjectConfig`.

**Comment by Quintenps** [comment] 2019-08-30 13:08
It seems that the issue is caused by the class `ArgvInput` not having the tokens parsed to options and arguments, causing  `$input->hasOption(Option::PROJECT_CONFIG_FILE)` never to result in True. By simply first running the parent method of `Application::doRun`

I think it can be very simply fixed by changing the order of `Application::doRun` and `Application::loadProjectConfig`.

**Comment by Quintenps** [comment] 2019-08-30 13:13
#37

**Closed** 2019-10-17 12:59 UTC
Labels: type/bug
